<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DreamAnalyzer2.Domain\DreamAnalyzer2.Domain.csproj" />
    <ProjectReference Include="..\DreamAnalyzer2.Shared\DreamAnalyzer2.Shared.csproj" />
  </ItemGroup>

</Project>
