// <auto-generated />
using System;
using DreamAnalyzer2.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DreamAnalyzer2.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525080841_FixAnalysisSymbolsForeignKey")]
    partial class FixAnalysisSymbolsForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DreamAnalysisDreamSymbol", b =>
                {
                    b.Property<Guid>("DreamAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SymbolsId")
                        .HasColumnType("uuid");

                    b.HasKey("DreamAnalysisId", "SymbolsId");

                    b.HasIndex("SymbolsId");

                    b.ToTable("AnalysisSymbols", (string)null);
                });

            modelBuilder.Entity("DreamAnalyzer2.Domain.Entities.Dream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DreamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dreams");
                });

            modelBuilder.Entity("DreamAnalyzer2.Domain.Entities.DreamAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DreamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DreamId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DreamId")
                        .IsUnique();

                    b.HasIndex("DreamId1")
                        .IsUnique();

                    b.ToTable("DreamAnalyses");
                });

            modelBuilder.Entity("DreamAnalyzer2.Domain.Entities.DreamSymbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DreamSymbols");
                });

            modelBuilder.Entity("DreamAnalyzer2.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DreamAnalysisDreamSymbol", b =>
                {
                    b.HasOne("DreamAnalyzer2.Domain.Entities.DreamAnalysis", null)
                        .WithMany()
                        .HasForeignKey("DreamAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamAnalyzer2.Domain.Entities.DreamSymbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DreamAnalyzer2.Domain.Entities.Dream", b =>
                {
                    b.HasOne("DreamAnalyzer2.Domain.Entities.User", null)
                        .WithMany("Dreams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DreamAnalyzer2.Domain.Entities.DreamAnalysis", b =>
                {
                    b.HasOne("DreamAnalyzer2.Domain.Entities.Dream", null)
                        .WithOne()
                        .HasForeignKey("DreamAnalyzer2.Domain.Entities.DreamAnalysis", "DreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamAnalyzer2.Domain.Entities.Dream", null)
                        .WithOne("Analysis")
                        .HasForeignKey("DreamAnalyzer2.Domain.Entities.DreamAnalysis", "DreamId1");

                    b.OwnsOne("DreamAnalyzer2.Domain.ValueObjects.Mood", "Mood", b1 =>
                        {
                            b1.Property<Guid>("DreamAnalysisId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ColorHex")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MoodColorHex");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MoodDescription");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MoodName");

                            b1.HasKey("DreamAnalysisId");

                            b1.ToTable("DreamAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("DreamAnalysisId");
                        });

                    b.Navigation("Mood")
                        .IsRequired();
                });

            modelBuilder.Entity("DreamAnalyzer2.Domain.Entities.Dream", b =>
                {
                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("DreamAnalyzer2.Domain.Entities.User", b =>
                {
                    b.Navigation("Dreams");
                });
#pragma warning restore 612, 618
        }
    }
}
